format = '($character)'
right_format = '''$git_branch$git_status$directory'''

# Disable the blank line at the start of the prompt
add_newline = false
command_timeout = 5000

[line_break]
disabled = true

[character]
success_symbol = "[ïŒ” ](bold blue)"
error_symbol = "[ïŒ” ](bold red)"
vicmd_symbol = "[î˜«](bold yellow)"


[directory]
format = " [$path](blue)"
truncation_length = 3
truncate_to_repo=false
disabled = false

[git_branch]
format = "[ó°˜¬ ](yellow)[$branch](yellow) "

[git_status]
format= "[ ó°Š¤ ](green)[$all_status$ahead_behind](green) "
conflicted = "="
ahead =	" ó°„¿ ${count}"
behind = " ó°„¼ ${count}"
diverged = " ó°„¿ ${ahead_count} ó°„¼ ${behind_count}"
up_to_date = " ó°„¬"
untracked = "?${count}"
stashed = "ó°–"
modified = "!${count}"
staged = "+${count}"
renamed = "*${count}"
deleted = "-${count}"

[sudo]
style = 'bold green'
symbol = 'ğŸ‘© '
disabled = false

[conda]
symbol = 'îœ¼ '
